# Get List
GET http://[::]:3000/product HTTP/1.1

###

# Get By Id
GET http://[::]:3000/product/1 HTTP/1.1

###

# Create
POST http://[::]:3000/product HTTP/1.1
Content-Type: application/json

{
  "productName": "W 產品",
  "authors": ["作者A、作者B、作者C"],
  "company": "博碩文化",
  "imgUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "price": 1580,
  "isShow": true,
  "vendue": false
}

###

# Update
PUT http://[::]:3000/product/2 HTTP/1.1
Content-Type: application/json

{
  "productName": "W 產品",
  "authors": ["作者A","作者B"],
  "company": "博碩文化",
  "imgUrl": "https://api.fnkr.net/testimg/200x200/DDDDDD/999999/?text=img",
  "price": 1580,
  "isShow": true,
  "vendue": true
}

###

# Delete
DELETE http://[::]:3000/product/2 HTTP/1.1
